### ISSUE TITLE
The PDP-10 normally deals with 36-bit words.

### ISSUE THREAD

**Issue by larsbrinkhoff** [caldwell/radix50#2]
I see the PDP-10 encode/decode deals with 16-bit words.  A PDP-10 word is 36 bits.  RADIX-50 would normally leave the four most significant bit unused.  Assemblers may encode symbols as six RADIX-50 characters in a word, and use the for extra bits for metadata about the symbol.

**Comment by caldwell** [comment]
Ah yes, I got that wrong, thanks. Since Rust doesn't have 36bit integer types and because 6 characters fits in 32 bits, I guess I should change the api to use `u32` in `pdp10::*` functions… Does that sound like what you would expect?

**Comment by larsbrinkhoff** [comment]
Yes, u32 would be much better.  Thanks!
